# Generated by Django 4.1.6 on 2023-02-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Lunch'), (1, 'Dinner'), (2, 'Breakfast')]),
        ),
    ]
