# Generated by Django 4.1.6 on 2023-02-04 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.SmallIntegerField(choices=[(0, 'Lunch'), (1, 'Dinner'), (2, 'Breakfast')])),
                ('food_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.food_item')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
