# Generated by Django 4.1.6 on 2023-02-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_food_item_menu_delete_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_items',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='food_item',
        ),
    ]
