# Generated by Django 4.1.6 on 2023-02-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_menu_food_items_delete_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_items',
        ),
    ]
