# Generated by Django 4.1.6 on 2023-02-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feedback_delete_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feed',
        ),
    ]
