# Generated by Django 4.1.6 on 2023-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('course', models.TextField(max_length=200)),
                ('semester', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
