# Generated by Django 4.1.6 on 2023-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mess_photo',
            field=models.ImageField(null=True, upload_to='messphotos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
