# Generated by Django 4.1.6 on 2023-02-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_mess_photo_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mess_photo',
            new_name='mess',
        ),
    ]
