# Generated by Django 4.1.6 on 2023-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_mess_photo_student_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mess',
            field=models.ImageField(null=True, upload_to='accounts/messphotos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='accounts/photos/'),
        ),
    ]
