# Generated by Django 4.1.6 on 2023-02-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_student_mess_alter_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='prof',
        ),
    ]
