# Generated by Django 4.1.6 on 2023-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_photo_student_prof"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="breakfast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meal",
            name="dinner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meal",
            name="lunch",
            field=models.BooleanField(default=False),
        ),
    ]
